### ISSUE TITLE
IConnection is missing executeMany function's typings. 

### ISSUE THREAD

**Issue by groovy21** [Bigous/typed-oracledb#1]
The latest version of the oracledb node package has a method called executeMany with 4 parameters. The IConnection interface in these typings are missing this method.

Please include it.

**Comment by Bigous** [comment]
Hi @groovy21 , my definitions were to version 1.11 of the library. It's now on version 3.1.1. Lots of things were added / changed from version 1.11 to 3.1.1. This repository was never considered official and you should refer to the [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) and not this one.
I'm not able to maintain this and it's only here to support old projects that use version 1.11 of oracledb library and was pointing to this repository using typings.
